version: 0.2

phases:
    install:
        commands:
            # Remember all commands will henceforth execute from `app`
            - cd app
            # - rm -rf node_modules/sharp
            - npm install --arch=x64 --platform=linux --target=10.14.1 sharp
            #- npm install
    pre_build:
        commands:
            - npm run test
    build:
        commands:
            - npm run build
            - tar -czvf ../camelothub.tar.gz public
artifacts:
    files:
        - camelothub.tar.gz
    discard-paths: yes