version: 0.2

phases:
    install:
        commands:
            # Remember all commands will henceforth execute from `app`
            - cd app
            - npm install
    pre_build:
        commands:
            - cp .env.$APP_ENV .env
    build:
        commands:
            - npm run build
            - ls -la
artifacts:
    files:
        - '**/*'
    base-directory: app/build