version: 0.2

phases:
    install:
        commands:
            # Remember all commands will henceforth execute from `app`
            - cd app
            - npm install
    pre_build:
        commands:
            #- npm run test
    build:
        commands:
            - npm run build
artifacts:
    files:
        - app/build