version: 0.2

phases:
    install:
        commands:
            # Remember all commands will henceforth execute from `app`
            - cd app
            - npm install
    pre_build:
        commands:
            #- npm run test
    build:
        commands:
            - echo "CODEBUILD_SRC_DIR:" . $CODEBUILD_SRC_DIR
            - npm run build
            - zip -r camelothub-$(date +%Y%m%d-%h%i%s).zip build
artifacts:
    files:
        - camelothub-$(date +%Y%m%d-%h%i%s).zip